import React from 'react'





const Data = () => {
    const EventsData=[
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
            
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
           
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
            
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
           
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
           
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
            
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
           
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
           
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
            
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
           
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
           
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
            
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
           
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
           
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
            
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
           
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
           
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
            
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
           
        },
        {
            title:"Cricket",
            subject:"cricket",
            photo:"/Images/profile.jpg",
            time:"jan 21st",
            status:"completed",
            description:"",
            rating:9,
            likes:1000,
        }
    
    ]
}

export default Data
